### ISSUE TITLE
Profile#createの作成

### ISSUE THREAD

**Issue by subaru-hello** [hiyoco-connect/hiyoco-connect#8]
### 概要
- Profile#createを作成する。
Viewは下記画像のようにする。
<a href="https://gyazo.com/5b09c2013c04bceb26b3b96d44576d1f"><img src="https://i.gyazo.com/5b09c2013c04bceb26b3b96d44576d1f.png" alt="Image from Gyazo" width="514"/></a>
### TODO
- Model
- [x] Profile.rbに下記記述を追加する
```ruby
accepts_nested_attributes_for :portfolios
```
- Controller
- [x] form_withから送られてきた値をprofile_params(ストロングパラメーター)で受け取る。
- [x] current_userに紐づくprofileクラスでportfolioインスタンスを作成する
- [x] 保存後、showにredirectさせる
- View
- [x] new.html.erbにform_withを設置する。
- [x] form_withの中にform_fieldをネストさせた形で記述。

**Comment by subaru-hello** [comment]
下記のようなエラーが出ました。[記事](https://stackoverflow.com/questions/36762779/ruby-on-rails-issues-using-enum-with-same-name)によると、_suffixを付ければ名前の衝突を回避できるそうなので、_suffixを追記します。
<a href="https://gyazo.com/f67ea317123d8d70a06cb0ef52bd7991"><img src="https://i.gyazo.com/f67ea317123d8d70a06cb0ef52bd7991.png" alt="Image from Gyazo" width="1275"/></a>

**Comment by subaru-hello** [comment]
メモ
ルーティングエラーが発生した
<a href="https://gyazo.com/e504710a8d75da6c46b82c63fe3c3da0"><img src="https://i.gyazo.com/e504710a8d75da6c46b82c63fe3c3da0.png" alt="Image from Gyazo" width="1262"/></a>
下記エラーの解消から始める
```ruby
ActionController::UrlGenerationError at /profiles/new
No route matches {:action=>"index", :controller=>"portfolios", :format=>nil, :profile_id=>#<Profile id: nil, name: nil, grade: nil, gender: "unanswered", birthplace_code: nil, living_place_code: nil, date_of_birth: nil, blood_type: "unanswered", siblings_relation: "unanswered", hobby: nil, times_name: nil, team_dev_will: "unanswered", twitter_account: nil, self_introduce: nil, avatar: nil, created_at: nil, updated_at: nil, user_id: nil>}, possible unmatched constraints: [:profile_id]
Did you mean?  profile_portfolios_url

**Comment by subaru-hello** [comment]
[立野さんからいただいた記事](https://yshrfmru.hatenablog.com/entry/2018/11/25/183126)を参考にして[こちらのエラー](https://github.com/hiyoco-connect/hiyoco-connect/issues/8#issuecomment-1040286768)を解消することができた。
